name: feature

on:
  workflow_dispatch:


concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linuxbuild:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: flucoma/actions/env@main
    - uses: flucoma/actions/sc@main
      with:
        branch: origin/main
        core_branch: origin/${{ github.ref_name }}
        build_type: "Test"
    - name: compress archive
      run: tar -zcvf FluCoMa-SC-Linux-x64-nightly.tar.gz FluidCorpusManipulation
      working-directory: install
    - uses: actions/upload-artifact@v4.3.6
      with:
        name: linuxbuild
        path: install/FluCoMa-SC-Linux-x64-nightly.tar.gz
